# Input constant parameters here.
t_dec: # Approximate deceleration time of burst.
densityProportionalityConstant: # Used for power law model.
powerLawIndex: # Power law index constant that dictates how quickly the density falls off .
radiusProportionalityConstant: # Used for radius function.
surroundingMediumDensity: # Number density of surrounding medium, in cm^-3.
initialEnergyEmitted:  # Initial energy emitted in erg.